trigger: none 

pool: default

name: Agentpat

steps: 
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azurenewconnection'
    backendAzureRmResourceGroupName: 'mriidulsrg'
    backendAzureRmStorageAccountName: 'mriidulstorage'
    backendAzureRmContainerName: 'mriidul-container-123'
    backendAzureRmKey: 'appkey.tfstate'
- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'azurenewconnection'
- task: TerraformTask@5
  displayName: terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve'